version: "3.5"
services:
  besu:
    build:
      context: build
      args:
        UPSTREAM_VERSION: 24.9.0
    ports:
      - 30415:30415/tcp
      - 30415:30415/udp
    volumes:
      - data:/var/lib/besu
    environment:
      STORAGE_FORMAT: BONSAI
      SYNC_MODE: SNAP
      BESU_RPC_HTTP_MAX_ACTIVE_CONNECTIONS: "250"
      BESU_RPC_WS_ENABLED: "true"
      P2P_PORT: "30415"
      BESU_OPTS: ""
      EXTRA_OPTS: ""
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
volumes:
  data: {}
