version: "3.5"
services:
  besu:
    build:
      context: build
      args:
        UPSTREAM_VERSION: 23.7.1
    ports:
      - "30414:30414/tcp"
      - "30414:30414/udp"
    volumes:
      - "data:/var/lib/besu"
    environment:
      EXTRA_OPTS: ""
      STORAGE_FORMAT: BONSAI
      SYNC_MODE: X_CHECKPOINT
      CONFIG_MODE: normal
      WS_ENABLED: "true"
      MAX_HTTP_CONNECTIONS: "170"
      P2P_PORT: "30414"
      BESU_OPTS: ""
    image: "besu.besu.public.dappnode.eth:1.2.1"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
volumes:
  data: {}
