version: "3.5"
services:
  besu:
    build:
      context: build
      args:
        UPSTREAM_VERSION: 24.4.0
    ports:
      - "30415:30415/tcp"
      - "30415:30415/udp"
    volumes:
      - "data:/var/lib/besu"
    environment:
      BESU_DATA_STORAGE_FORMAT: BONSAI
      BESU_SYNC_MODE: X_CHECKPOINT
      BESU_RPC_HTTP_MAX_ACTIVE_CONNECTIONS: "170"
      BESU_RPC_WS_ENABLED: "true"
      P2P_PORT: "30415"
      BESU_OPTS: ""
      EXTRA_OPTS: ""
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
volumes:
  data: {}
